In [1]:
import numpy as np

In [11]:
a = np.random.randint(1, 10, size=(3,3)) #Create an array with random integer between 1 and 10 with 3 rows, 3 columns)

In [12]:
a

array([[7, 5, 2],
       [6, 5, 3],
       [3, 7, 8]])

In [13]:
a[1:, 2:] #To slice an array it is necessary to define slice on rows and columns

array([[3],
       [8]])

In [14]:
b = a[1:, :2] #b is a view not a data structure

In [15]:
b

array([[6, 5],
       [3, 7]])

In [19]:
a[1, 1] = 35 #Numpy array are mutable

In [17]:
a

array([[ 7,  5,  2],
       [ 6, 35,  3],
       [ 3,  7,  8]])

In [20]:
b #Means that b slice will retrieve changes on a

array([[ 6, 35],
       [ 3,  7]])

In [26]:
a = np.random.randint(1, 10, size=(4, 4)) #Create a 4 x 4 array with random int

In [23]:
a

array([[4, 6, 6, 8],
       [5, 8, 5, 6],
       [1, 4, 8, 5],
       [7, 1, 9, 1]])

In [27]:
b = a.reshape(8, 2) # reshaped matrix must have the same number of elements

In [25]:
b

array([[4, 6],
       [6, 8],
       [5, 8],
       [5, 6],
       [1, 4],
       [8, 5],
       [7, 1],
       [9, 1]])

In [28]:
mars = np.random.randint(-5, 20, size=31)

In [29]:
mars

array([-5, -4,  6, 14, 10, 17,  5,  5, -5, 16,  5, 16, -4, -4, 15, 10,  5,
       -1,  9,  7,  7,  9, -1, -2,  5, 19,  0,  4, -3, 19, 14])

In [31]:
mars > 0 # It performs comparisons on all elements of the array

array([False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True, False,
        True, False,  True,  True])

In [32]:
mars == 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False])

In [33]:
np.sum(mars > 0) #Make the sum of all true values

21

In [34]:
np.any(mars == 20) #Return True is any value is True

False

In [35]:
np.all(mars >0) #Return True is all values are True

False

In [36]:
jours_mars = np.arange(1, mars.size +1, dtype =np.int8 )

In [37]:
jours_mars

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], dtype=int8)

In [39]:
np.sum((mars > 10 ) & (jours_mars >=15)) #Return number of days where temperature > 10° since march 15th

4

In [41]:
mars[mars>10] #Return values > 10

array([14, 17, 16, 16, 15, 19, 19, 14])

In [43]:
mars[(mars>10) & (jours_mars>=15)] #Return values > 10 after march 15h

array([15, 19, 19, 14])

In [47]:
moy = np.mean(mars[mars>0]) #Retrieve mean of positive values

In [48]:
mars[mars<0] = moy #Replace all negative values with the mean of positives ones

In [46]:
mars

array([10, 10,  6, 14, 10, 17,  5,  5, 10, 16,  5, 16, 10, 10, 15, 10,  5,
       10,  9,  7,  7,  9, 10, 10,  5, 19,  0,  4, 10, 19, 14])

In [49]:
countries = np.array(['fr', 'us', 'jp'])

In [50]:
countries

array(['fr', 'us', 'jp'], dtype='<U2')

In [51]:
countries[[0, 0, 1, 2, 0]]

array(['fr', 'fr', 'us', 'jp', 'fr'], dtype='<U2')