In [3]:
import numpy as np

In [4]:
print(np.array([1,2,3])) # declare a normal array filled by a list

[1 2 3]


In [8]:
z = np.zeros(10) # declare 10 size zero array / vector
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
z = np.zeros((10,10)) # declare a 10x10 zero matrix
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
o = np.ones((10,10)) # declare a 10x10 ones array
print(o)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
r = np.random.random((10,10)) # declare a 10x10 random matrix
print(r)

[[0.72733001 0.15827076 0.5845349  0.88669542 0.30977461 0.93390011
  0.36217856 0.023277   0.06622402 0.5891951 ]
 [0.06464589 0.2557179  0.19961562 0.00809146 0.34264275 0.61471677
  0.04406475 0.76316509 0.38439215 0.02536662]
 [0.38968667 0.09484728 0.66027843 0.04452392 0.29349566 0.8371196
  0.35491329 0.67579219 0.76706994 0.14069517]
 [0.28849511 0.42882378 0.48026403 0.01340202 0.89711135 0.10228545
  0.75528557 0.87966121 0.72926259 0.56099628]
 [0.64137566 0.13871148 0.65894608 0.12884989 0.36327454 0.85295567
  0.24444931 0.91703454 0.29968893 0.48847242]
 [0.98184959 0.4786663  0.08037979 0.3909993  0.87222063 0.6365443
  0.99548723 0.99742056 0.33230267 0.50285412]
 [0.40553384 0.67279396 0.21004075 0.01828554 0.24883473 0.97353893
  0.73105039 0.79292329 0.92398215 0.5228832 ]
 [0.27872527 0.18078526 0.09676093 0.88615347 0.48551199 0.47332895
  0.90546473 0.26078812 0.88337437 0.13525131]
 [0.56315305 0.26130192 0.40527571 0.33542138 0.56600559 0.00280595
  0.54416886 0

In [19]:
G = np.random.randn(10,10) # declare a 10x10 random matrix with a normal (gaussian) distribution
print(G)

[[ 2.25612818e-01  2.52617775e+00  7.45235926e-01 -6.17650308e-01
  -5.49798755e-01 -1.41174130e+00  5.42749268e-01 -3.50145532e-04
   2.14055333e+00 -1.82723999e+00]
 [ 3.14057791e-01  1.47629321e+00  1.45192286e+00 -6.72042167e-01
  -5.55013701e-01 -4.03988053e-01 -1.04819142e+00 -3.03051849e-01
  -2.78854633e-01  1.36202172e+00]
 [-4.38268678e-01  9.87439534e-01  8.94132096e-01 -3.17115269e-01
   1.26938069e+00  5.39023632e-01  2.38005833e-01 -2.13196452e+00
   4.11570025e-01  3.32124126e-01]
 [ 1.15834009e+00 -7.75859422e-01 -1.09462741e+00  2.11510748e-01
   9.21477960e-01  4.05375948e-01  1.02225900e-01 -5.25437238e-01
   1.10396423e+00  1.41125954e+00]
 [-1.36858210e+00 -1.17096068e+00 -1.92174842e-01 -6.43567760e-01
   2.50188720e-01 -8.97264384e-02  9.42406334e-02 -2.10770161e+00
   4.70149021e-01 -4.55396512e-01]
 [-3.62515754e-02 -1.32940828e+00  7.68184323e-01  1.48318482e-01
  -1.31423569e-02  1.02575133e+00 -1.38007069e+00  9.25600032e-01
  -2.82344649e-02 -9.97933083e-01

In [20]:
print(G.mean()) # print the mean of a G

0.1059677095741326


In [21]:
print(G.var()) # print the variance of a G

1.0223644175659183
