In [4]:
import numpy as np

In [14]:
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A) # returns inverse of a matrix
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
print(Ainv.dot(A)) #test : multiply A by invA returns an identity matrix

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [8]:
print(A.dot(Ainv))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [10]:
print(np.linalg.det(A)) # print A determinent

-2.0000000000000004


In [11]:
print(np.diag(A)) # print diagonal elements of a matrix in a diagonal

[1 4]


In [12]:
print(np.diag([1,2])) # print 2D array with given values in arguments in a diagonal and zeros 

[[1 0]
 [0 2]]


In [6]:
a = np.array([1,2])
b = np.array([3,4])

In [14]:
print(np.outer(a,b))

[[3 4]
 [6 8]]


In [7]:
print(np.inner(a,b))

11


In [8]:
print(a.dot(b))

11


In [15]:
print(np.diag(A).sum()) #return sum of diagonal of an array

5


In [16]:
print(np.trace(A)) #return sum of diagonal of an array

5


In [17]:
X = np.random.randn(100,3)

In [18]:
print(X)

[[ 6.46680555e-01 -1.60066830e-01 -7.78844501e-02]
 [-1.25279015e+00 -1.94010651e-01 -3.19830940e-01]
 [ 1.79845584e-02  1.08777230e+00 -3.52299798e-01]
 [-7.93256767e-01 -9.53324863e-01 -5.05608824e-01]
 [-3.60095596e-01  6.16089515e-01 -1.33804567e+00]
 [ 3.07689042e-01 -1.52325599e-01  3.30579051e-01]
 [-8.49146716e-01  1.12708486e+00 -1.67425459e+00]
 [-1.46548523e+00  1.63944267e+00  7.86809853e-01]
 [-8.46274589e-01 -7.31858749e-01 -6.47188169e-01]
 [-1.54254454e+00  5.35660717e-01 -8.73341536e-01]
 [ 2.39770719e-01  5.54080279e-01 -2.30269892e-01]
 [-1.21705740e+00 -1.44581019e+00 -6.10622432e-01]
 [ 5.46170024e-01 -2.34262646e-01 -3.40263302e-02]
 [ 2.95549866e-01  1.43537685e-01 -8.92787452e-01]
 [ 6.41396646e-01  1.20838281e+00  2.24236440e+00]
 [-2.19593145e-01  1.14738161e+00 -1.01807277e+00]
 [ 6.13459498e-01 -2.37840599e+00  8.84344112e-03]
 [-1.37038005e+00  2.09923499e-01 -9.70981190e-01]
 [ 3.81813197e-01  1.10142629e+00 -6.56120297e-01]
 [ 1.77380551e+00 -9.39515970e-

In [19]:
cov = np.cov(X)

In [21]:
cov.shape

(100, 100)

In [22]:
cov = np.cov(X.T)

In [23]:
cov

array([[ 1.14313053, -0.1135488 , -0.08080477],
       [-0.1135488 ,  0.92724527,  0.08173946],
       [-0.08080477,  0.08173946,  0.95027806]])

In [24]:
np.linalg.eigh(cov)

(array([0.85044119, 0.93744791, 1.23276476]),
 array([[-0.17221271,  0.5149019 , -0.83977307],
        [-0.82592825,  0.38911737,  0.40795857],
        [ 0.53682893,  0.76384796,  0.35826107]]))

In [25]:
np.linalg.eigh(cov)

(array([0.85044119, 0.93744791, 1.23276476]),
 array([[-0.17221271,  0.5149019 , -0.83977307],
        [-0.82592825,  0.38911737,  0.40795857],
        [ 0.53682893,  0.76384796,  0.35826107]]))