In [2]:
import numpy as np

In [6]:
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A) # returns inverse of a matrix
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
print(Ainv.dot(A)) #test : multiply A by invA returns an identity matrix

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [8]:
print(A.dot(Ainv))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [10]:
print(np.linalg.det(A)) # print A determinent

-2.0000000000000004


In [11]:
print(np.diag(A)) # print diagonal elements of a matrix in a diagonal

[1 4]


In [12]:
print(np.diag([1,2])) # print 2D array with given values in arguments in a diagonal and zeros 

[[1 0]
 [0 2]]


In [13]:
a = np.array([1,2])
b = np.array([3,4])

In [14]:
print(np.outer(a,b))

[[3 4]
 [6 8]]
