In [1]:
import numpy as np

In [2]:
L = [1,2,3]
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)
print(L)

[1, 2, 3, 4, 4]


In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L += [5]
print(L)

[1, 2, 3, 4, 4, 5]


In [10]:
A += [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) (3,) 

In [11]:
L2 = []

for e in L:
    L2.append(e + e)

print(L2)

[2, 4, 6, 8, 8, 10]


In [14]:
print(A+A)

[2 4 6]


In [15]:
print(2 * A)

[2 4 6]


In [16]:
print(2 * L)

[1, 2, 3, 4, 4, 5, 1, 2, 3, 4, 4, 5]


In [17]:
print(L ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
L2 = []
for e in L:
    L2.append(e ** 2)
print(L2)

[1, 4, 9, 16, 16, 25]


In [19]:
print(A ** 2)

[1 4 9]


In [20]:
print(np.sqrt(A))

[1.         1.41421356 1.73205081]


In [21]:
print(np.log(A))

[0.         0.69314718 1.09861229]
